set nu
set ai
set tabstop=4
set shiftwidth=4
set bg=dark
set cursorline

set ruler
set expandtab
syntax on

" enable filetype detection:
filetype on
filetype plugin on
filetype indent on

" in makefiles, don't expand tabs to spaces, since actual tab characters are
" needed, and have indentation at 8 chars to be sure that all indents are tabs
" (despite the mappings later):
autocmd FileType Makefile set noexpandtab shiftwidth=8 softtabstop=0
