if has("spell")
  " turn spelling on by default
  set spell

  " toggle spelling with F4 key
  " map <F4> :set spell!<CR><Bar>:echo "Spell Check: " . strpart("OffOn", 3 * &spell, 3)<CR>

  " they were using white on white
  highlight PmenuSel ctermfg=black ctermbg=lightgray

  " limit it to just the top 10 items
  " set sps=best,10                    
endif

syntax on
colo blue

set expandtab
set tabstop=4
set shiftwidth=4
" set term=builtin_ansi

